export const TOGGLE_AUTH_MODAL_VISIBLE = 'TOGGLE_AUTH_MODAL_VISIBLE';
export const TOGGLE_UPDATE_VISIBLE = 'TOGGLE_UPDATE_VISIBLE';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA';
export const REMOVE_PROFILE_DATA = 'REMOVE_PROFILE_DATA';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHANGE_STEP = 'CHANGE_STEP';