export const UPDATE_CHAT_HISTORY = 'UPDATE_CHAT_HISTORY';
export const UPDATE_CHATS_STATUS = 'UPDATE_CHATS_STATUS';
export const UPDATE_CURRENT_COMPANION = 'UPDATE_CURRENT_COMPANION';
export const UPDATE_READ_MESSAGES = 'UPDATE_READ_MESSAGES';
export const UPDATE_NEW_MESSAGES = 'UPDATE_NEW_MESSAGES';
export const CLEAR_CHAT = 'CLEAR_CHAT';
export const CLEAR_CHAT_HISTORY = 'CLEAR_CHAT_HISTORY';